import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import BranchBadge from "../../../../shared/BranchBadge";
import { IoArrowBack } from "react-icons/io5";
import { BsSearch } from "react-icons/bs";
import { CiExport } from "react-icons/ci";
import { toast } from "react-toastify";
import logo from "../../../../../assets/images/adminLogo.png";
import {
  createFundTransfer,
  getAccountOptions,
  getFundTransfers,
} from "../../../../../lib/accountingApi";
import { cashierApi } from "../../../../../lib/cashierApi";
import AccountPicker from "../../../../shared/AccountPicker";
import { useAuth } from "../../../../../context/AuthContext";
import "../../../Account.css";

const FundTransfers = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [form, setForm] = useState({
    glAccount: "",
    customerId: "",
    accountName: "",
    description: "",
    referenceNo: "",
    transactionDate: new Date().toISOString().slice(0, 10),
    amount: "",
    entryType: "DEBIT",
  });
  const [rows, setRows] = useState([]);
  const [accountOptions, setAccountOptions] = useState([]);
  const [customers, setCustomers] = useState([]);
  const [loadingRows, setLoadingRows] = useState(false);
  const [saving, setSaving] = useState(false);

  const loadFundTransfers = async () => {
    setLoadingRows(true);
    try {
      const savedRows = await getFundTransfers();
      setRows(savedRows);
    } catch (error) {
      console.error("Failed to load fund transfers:", error);
      toast.error(error.message || "Unable to load fund transfers");
    } finally {
      setLoadingRows(false);
    }
  };

  useEffect(() => {
    loadFundTransfers();
    const loadAccounts = async () => {
      try {
        const accounts = await getAccountOptions();
        setAccountOptions(accounts);
      } catch (error) {
        console.error("Failed to load fund transfer account options:", error);
        toast.error(error?.message || "Unable to load backend account IDs");
        setAccountOptions([]);
      }
    };
    const loadCustomers = async () => {
      try {
        const directory = await cashierApi.getCustomerDirectory();
        setCustomers(directory);
      } catch (error) {
        console.error("Failed to load customers:", error);
        setCustomers([]);
      }
    };
    loadAccounts();
    loadCustomers();
  }, []);

  const handleChange = (event) => {
    const { name, value } = event.target;
    setForm((prev) => ({ ...prev, [name]: value }));
  };

  const clearForm = () => {
    setForm((prev) => ({
      ...prev,
      glAccount: "",
      customerId: "",
      accountName: "",
      description: "",
      amount: "",
      entryType: "DEBIT",
    }));
  };

  const handlePost = async () => {
    if (!form.glAccount.trim()) {
      toast.error("Please select the company account to debit");
      return;
    }
    if (!form.customerId.trim()) {
      toast.error("Please select the customer whose wallet will be funded");
      return;
    }

    const parsedAmount = Number(form.amount);
    if (!parsedAmount || parsedAmount <= 0) {
      toast.error("Please enter a valid AMOUNT");
      return;
    }

    const fromAccountId = Number(form.glAccount);
    if (!fromAccountId) {
      toast.error("Company account must be a valid GL account");
      return;
    }

    const userId = Number(user?.id ?? user?.userId ?? user?.user_id);
    if (!userId) {
      toast.error("User session is missing ID. Please log in again.");
      return;
    }

    // Fund the selected customer's wallet from the company account. Reference number
    // and transaction date are generated by the backend.
    const payload = {
      fromAccountId,
      customerId: Number(form.customerId) || undefined,
      description: form.description.trim(),
      amount: parsedAmount,
    };

    setSaving(true);
    try {
      const createdRow = await createFundTransfer({ userId, transferPayload: payload });
      setRows((prev) => [createdRow, ...prev]);
      toast.success("Fund transfer posted successfully");
      clearForm();
    } catch (error) {
      console.error("Failed to post fund transfer:", error);
      toast.error(error.message || "Unable to post fund transfer");
    } finally {
      setSaving(false);
    }
  };

  const selectedCustomer = useMemo(
    () => customers.find((c) => String(c.id) === String(form.customerId)) || null,
    [customers, form.customerId]
  );

  const totals = useMemo(() => {
    return rows.reduce(
      (acc, row) => {
        acc.debit += Number(row.debit) || 0;
        acc.credit += Number(row.credit) || 0;
        return acc;
      },
      { debit: 0, credit: 0 }
    );
  }, [rows]);

  const balanceDiff = totals.debit - totals.credit;
  const emptyRows = Math.max(0, 6 - rows.length);

  return (
    <div className="journal-page">
      <nav className="bg-primary d-flex align-items-center justify-content-between px-5">
        <Link to="/adminDashboard">
          <img src={logo} alt="pm logo" className="logo-acc" />
        </Link>
        <div className="d-flex">
            <div className="dropdown-center acc-dropdown-link">
            <button
              className="btn text-white dropdown-toggle"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              JOURNAL
            </button>
            <ul className="dropdown-menu">
              <li>
                <Link to="/Accounting/JournalEntry" className="text-decoration-none text-dark">
                  Journal Entry
                </Link>
              </li>
              <li>
                <Link to="/Accounting/JournalEdit" className="text-decoration-none text-dark">
                  Journal Edit
                </Link>
              </li>
            </ul>
          </div>
          <div className="dropdown-center acc-dropdown-link">
            <button
              className="btn text-white dropdown-toggle"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              TRANSFERS
            </button>
            <ul className="dropdown-menu">
              <li>
                <Link to="/Accounting/FundTransfers" className="text-decoration-none text-dark">
                  Fund transfers
                </Link>
              </li>
              <li>
                <Link to="/Accounting/TransactionView" className="text-decoration-none text-dark">
                  Transaction View
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <Link to="/">
          <button className="Log_Out-btn cl-log-out" id="Log_Out-btn-sm">
            Log Out
          </button>
        </Link>
      </nav>

      <div className="acc-type-container journal-container">
        <div className="d-flex align-items-center mb-4 journal-title-row">
           <button
             type="button"
             className="acc-type-back-btn me-3"
             onClick={() => navigate("/Accounting/Transaction")}
             aria-label="Go back to transaction"
           >
             <IoArrowBack size={20} />
           </button>
           <h4 className="text-uppercase text-primary fw-bold m-0">Fund Transfers</h4>
           <div style={{ display: "flex", alignItems: "center", marginLeft: "1rem" }}>
             <BranchBadge />
           </div>
        </div>

        <div className="row g-4 mb-4 journal-form-shell">
          <div className="col-md-6">
            <div className="row mb-3 align-items-center journal-field-row">
              <label className="col-sm-4 fw-bold text-primary">Company Account (to Debit)</label>
              <div className="col-sm-8">
                <AccountPicker
                  accounts={accountOptions}
                  value={form.glAccount}
                  onChange={(nextValue) =>
                    setForm((prev) => ({ ...prev, glAccount: nextValue }))
                  }
                  placeholder="Search company GL account by ID (e.g. 1020101) or name"
                />
              </div>
            </div>
            <div className="row mb-3 align-items-center journal-field-row">
              <label className="col-sm-4 fw-bold text-primary">Customer</label>
              <div className="col-sm-8 position-relative">
                <select
                  className="form-select border-primary-subtle"
                  name="customerId"
                  value={form.customerId}
                  onChange={handleChange}
                >
                  <option value="">Select customer</option>
                  {customers.map((customer) => (
                    <option key={`cust-${customer.id}`} value={customer.id}>
                      {customer.customerName || "Customer"}
                      {customer.accountNumber ? ` — ${customer.accountNumber}` : ""}
                    </option>
                  ))}
                </select>
                <BsSearch className="position-absolute end-0 top-50 translate-middle-y me-3 text-secondary" />
              </div>
            </div>
            {selectedCustomer && (
              <div className="row mb-3 align-items-center journal-field-row">
                <label className="col-sm-4 fw-bold text-primary">Customer Wallet</label>
                <div className="col-sm-8">
                  <div className="border border-primary-subtle rounded p-2 bg-light">
                    <div>
                      <span className="text-secondary">Wallet Number: </span>
                      <strong>{selectedCustomer.accountNumber || "—"}</strong>
                    </div>
                    <div>
                      <span className="text-secondary">Account Name: </span>
                      <strong>{selectedCustomer.customerName || "—"}</strong>
                    </div>
                  </div>
                </div>
              </div>
            )}
             <div className="row mb-3 journal-field-row">
              <label className="col-sm-4 fw-bold text-primary">Description</label>
              <div className="col-sm-8">
                <textarea
                  className="form-control border-primary-subtle"
                  rows="3"
                  name="description"
                  value={form.description}
                  onChange={handleChange}
                ></textarea>
              </div>
            </div>
          </div>

          <div className="col-md-6">
            <div className="row mb-3 align-items-center journal-field-row">
              <label className="col-sm-4 fw-bold text-primary">Amount</label>
              <div className="col-sm-8">
                <input
                  type="number"
                  min="0"
                  step="0.01"
                  className="form-control border-primary-subtle"
                  name="amount"
                  value={form.amount}
                  onChange={handleChange}
                />
              </div>
            </div>
            <div className="row mb-3 journal-field-row">
              <div className="col-sm-8 offset-sm-4">
                <small className="text-secondary">
                  Reference number and transaction date are generated automatically.
                </small>
              </div>
            </div>
             <div className="text-end mt-4">
                <button
                  className="btn btn-primary px-5 py-2 fw-bold journal-primary-btn"
                  type="button"
                  onClick={handlePost}
                  disabled={saving}
                >
                  {saving ? "POSTING..." : "POST"}
                </button>
            </div>
          </div>
        </div>

        <div className="d-flex justify-content-end mb-2 journal-export-row">
            <button className="btn btn-sm btn-outline-primary border-0 d-flex align-items-center gap-2">
                Export to excel <CiExport size={20} />
            </button>
        </div>

        <div className="table-responsive acc-type-container-table mb-3 journal-table-wrap" style={{height: '400px'}}>
          <table className="table table-striped table-hover journal-entry-table">
            <thead className="bg-primary text-white">
              <tr>
                <th scope="col" className="bg-primary text-white">ACCOUNT ID</th>
                <th scope="col" className="bg-primary text-white">ACCOUNT NAME</th>
                <th scope="col" className="bg-primary text-white">DESCRIPTION</th>
                <th scope="col" className="bg-primary text-white text-end">DEBIT</th>
                <th scope="col" className="bg-primary text-white text-end">CREDIT</th>
              </tr>
            </thead>
            <tbody>
                {loadingRows && (
                  <tr style={{ height: "3rem" }}>
                    <td colSpan="5" className="text-center fw-semibold">
                      Loading fund transfers...
                    </td>
                  </tr>
                )}
                {!loadingRows &&
                  rows.map((row) => (
                    <tr key={row.id} style={{ height: "3rem" }}>
                      <td>{row.accountId}</td>
                      <td>{row.accountName}</td>
                      <td>{row.description}</td>
                      <td className="text-end">{Number(row.debit).toFixed(2)}</td>
                      <td className="text-end">{Number(row.credit).toFixed(2)}</td>
                    </tr>
                  ))}
                {!loadingRows &&
                  [...Array(emptyRows)].map((_, i) => (
                    <tr key={`empty-${i}`} style={{ height: "3rem" }}>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                      <td></td>
                    </tr>
                  ))}
            </tbody>
             <tfoot className="position-sticky bottom-0">
                <tr className="bg-primary text-white">
                    <td colSpan="3" className="bg-primary text-white fw-bold ps-4">TOTALS</td>
                    <td className="bg-primary text-white text-end fw-bold">{totals.debit.toFixed(2)}</td>
                    <td className="bg-primary text-white text-end fw-bold pe-2">{totals.credit.toFixed(2)}</td>
                </tr>
            </tfoot>
          </table>
        </div>

        <div className="d-flex justify-content-between align-items-center mb-4 journal-footer-row">
             <div className="d-flex gap-3">
                 <button className="btn btn-outline-primary px-5 fw-bold" type="button" onClick={clearForm}>CLEAR</button>
                 <button className="btn btn-outline-primary px-5 fw-bold">DELETE</button>
             </div>
             <div className="d-flex align-items-center gap-3">
                 <label className="fw-bold text-primary">BALANCE :</label>
                 <input
                   type="text"
                   className="form-control border-primary-subtle text-end"
                   style={{width: '150px'}}
                   value={balanceDiff.toFixed(2)}
                   disabled
                 />
             </div>
        </div>

         <div className="d-flex gap-3 mb-5">
             <button className="btn btn-primary px-5 py-2 fw-bold journal-primary-btn">EDIT</button>
             <button className="btn btn-primary px-5 py-2 fw-bold journal-primary-btn">SAVE</button>
         </div>

      </div>
    </div>
  );
};

export default FundTransfers;
